In [1]:
import pandas as pd
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

In [2]:
analyzer = SentimentIntensityAnalyzer()

In [3]:
df = pd.read_csv('../data/raw/mastodon.csv')
df

,topic,text,created_at,likes,reblogs,replies,followers,text_clean
0,politics,New Unredacted Banner Installed on DOJ exterio...,2026-02-19 19:50:30.066000+00:00,0,2,0,0,new unredacted banner installed on doj exterior
1,politics,"Verzweiflung:""parallel zu den dreiseitigen Ges...",2026-02-19 19:46:19+00:00,0,0,0,222,"verzweiflung:""parallel zu den dreiseitigen ges..."
2,politics,🚨Epstein NM Ranch DEMOLISHED after INVESTIGATI...,2026-02-19 19:45:06.010000+00:00,0,1,0,79,🚨epstein nm ranch demolished after investigati...
3,politics,‘They pushed so many lies about recycling’: th...,2026-02-19 19:43:06+00:00,0,2,0,436,‘they pushed so many lies about recycling’: th...
4,politics,Buttigieg leads 2028 presidential primary fiel...,2026-02-19 19:40:08.892000+00:00,0,2,0,79,buttigieg leads 2028 presidential primary fiel...
...,...,...,...,...,...,...,...,...
5799,sports,Short-handed Warriors earn one of their best w...,2026-03-06 07:30:03+00:00,0,0,0,921,short-handed warriors earn one of their best w...
5800,sports,Crystal Palace have some momentum again https:...,2026-03-06 07:15:02+00:00,0,0,0,921,crystal palace have some momentum again victor...
5801,sports,Why is everyone so upset about Arsenal's game ...,2026-03-06 07:10:02+00:00,0,0,0,921,why is everyone so upset about arsenal's game ...
5802,sports,Sean Dyche 'doesn't understand' Nottingham For...,2026-03-06 07:05:03+00:00,0,0,0,921,sean dyche 'doesn't understand' nottingham for...
5803,sports,Jeux Paralympiques de Milan-Cortina 2026 : la ...,2026-03-06 06:41:20.481000+00:00,0,0,0,35,jeux paralympiques de milan-cortina 2026 : la ...

In [ ]:
#embaralha as linhas
df = df.sample(frac=1, random_state=42).reset_index(drop=True)

In [5]:
sentiment_score = []

In [6]:
for text in df['text_clean']:
    text = str(text)

    scores = analyzer.polarity_scores(text)
    compound_score = scores["compound"]

    sentiment_score.append(compound_score)

In [7]:
df["sentiment_score"] = sentiment_score

In [8]:
labels = []

In [9]:
for score in df['sentiment_score']:
    if score > 0.05:
        labels.append(1) #comentario positivo
    
    elif score < -0.05:
        labels.append(-1) #comentario negativo
    
    else:
        labels.append(0) #comentario neutro

In [10]:
df['labels'] = labels

In [11]:
df = df.dropna()
df

,topic,text,created_at,likes,reblogs,replies,followers,text_clean,sentiment_score,labels
0,climate,‘Playing Checkers’: Trump’s Bid to Revive Coal...,2026-02-19 00:28:04+00:00,0,0,0,160,‘playing checkers’: trump’s bid to revive coal...,0.4019,1
1,health,🧠💤 Ever feel like your #brain is still solving...,2026-02-26 22:30:00+00:00,3,7,0,1059,🧠💤 ever feel like your brain is still solving ...,0.7269,1
2,politics,It's fascinating that Manchester's Ellen Wilki...,2026-02-28 06:04:09.517000+00:00,1,2,0,76,it's fascinating that manchester's ellen wilki...,0.6249,1
3,science,P ≠ NP: Checking a solution is easy; finding i...,2026-02-28 07:39:13+00:00,0,0,0,114,p ≠ np: checking a solution is easy; finding i...,0.9217,1
4,climate,Mark Carney’s pipeline MOU with Danielle Smith...,2026-03-06 11:49:04+00:00,0,0,0,163,mark carney’s pipeline mou with danielle smith...,-0.9287,-1
...,...,...,...,...,...,...,...,...,...,...
5799,politics,#gazetadobrasil #jornalismo #noticias #politic...,2026-02-28 06:49:16.843000+00:00,0,0,0,150,gazetadobrasil jornalismo noticias politics ar...,-0.2960,-1
5800,health,Alaska Man Develops Rare 'Seal Finger' Infecti...,2026-03-05 19:06:08+00:00,0,0,0,325,alaska man develops rare 'seal finger' infecti...,0.0000,0
5801,health,"Bei meinem EKG heute morgen sagte die Ärztin, ...",2026-03-05 15:21:53+00:00,0,0,0,14,"bei meinem ekg heute morgen sagte die ärztin, ...",-0.5994,-1
5802,economy,"Alberta returning to standard, flat tax on win...",2026-03-05 20:32:05+00:00,0,0,0,37,"alberta returning to standard, flat tax on win...",0.3182,1
5803,economy,A big cricket game between India and Pakistan ...,2026-02-19 08:31:43.785000+00:00,0,1,0,13,a big cricket game between india and pakistan ...,0.8519,1

In [12]:
df['labels'].value_counts()

labels
 1    2261
-1    1805
 0    1736
Name: count, dtype: int64

In [13]:
df["labels"].value_counts(normalize=True)

labels
 1    0.389693
-1    0.311100
 0    0.299207
Name: proportion, dtype: float64

In [14]:
df.to_csv('../data/raw/labeled_mastodon.csv', index= False)